select * from fact
select * from Location
select * from Product

--Display the number of states present in the LocationTable
SELECT COUNT(DISTINCT State) AS NumberOfStates
FROM Location;

--How many products are of regular type?
SELECT COUNT(type) AS NumofType
FROM Product
WHERE product.type = 'regular';


--How much spending has been done on marketing of product ID 1?
SELECT SUM(marketing) AS TotalMkSpend
FROM fact
WHERE ProductId = 1;

--How much spending has been done on marketing of product ID 1?

select sum(Marketing) as totalMKSpend from fact
where ProductId =1;

--Display the details of the product where product type is coffee.

select * from Product
where Product.Product_Type ='Coffee';

--Display the details where total expenses are greater than 40.

select * from fact
where Total_Expenses > '40';

--What is the average sales in area code 719?

select AVG (Sales) As Total_Avg_sales_in_719
from fact
where Area_Code = '719';

select * from fact

--Find out the total profit generated by Colorado state

select sum (Profit) as total_profit
from fact
Inner Join Location ON fact.Area_Code= Location.Area_Code
where Location.State  = 'Colorado';

            -- or
                       
select sum (Profit) as total_profit
from fact
where Area_Code in (select Area_Code from Location where State = 'Colorado');


--Find the state wise profit and sales

  select l.state , sum(f.Profit) as TotalProfit,
       sum(f.Sales) as Totalsales
   from fact f
   inner join Location l on f.Area_Code=l.Area_Code
   group by l.State


 --If there is an increase in sales of 5%, calculate the increasedsales.
   select ProductId,Sales, Sales*1.05 as increase_sales from fact 


--Display the ASCII value of the fifth character from the columnProduct.
select ASCII(SUBSTRING(PRODUCT,5,1)) AS ASCII_VALUE FROM Product;


--What is the minimum sales of a product?

select MIN(Sales) as Minimum_Sales from fact;

--Display the max Cost of Good Sold (COGS).
select MAX(COGS) as max_cogs from fact;



--Display the average inventory for each product ID.

select ProductId, AVG(Inventory) as total_invertory from fact
group by ProductId;

--Display state in a sequential order in a Location Table. 

select State from Location order by State ASC;


/* Display the average budget of the Product where the average budget
margin should be greater than 100. */

select ProductId, AVG(Budget_Profit) as avg_profit,
                  AVG(Budget_COGS) as avg_cogs,
                  AVG(Budget_Margin) as avg_margin,
                  AVG(Budget_Sales) as avg_sales
from fact
where Budget_Margin > = '100'
group by ProductId;


--What is the total sales done on date 2010-01-01?

select Sales , count(*) as total_sales from fact
where Date = '2010-01-01'
group by Sales;

--Display the average total expense of each product ID on an individual date.

select ProductId ,Date ,AVG (Total_Expenses) as avg_total_expense  from fact
group by ProductId , Date
order by ProductId ASC;


--Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code.

/* select *  from fact
select * from Product
select * from Location */

select F.Date,
       P.ProductId,
       P.Product_Type,
       P.Product,
       F.Sales,
       F.Profit,
       L.State,
       L.Area_Code

from fact as f
Inner Join Product As P on F.ProductId = P.ProductId
Inner Join Location As L on F.Area_Code = L.Area_Code;

--Display the rank without any gap to show the sales wise rank.

 select Date, ProductId, Sales, 
 DENSE_RANK() OVER (ORDER BY sales DESC) AS sales_rank
 from fact;

 --Find the state wise profit and sales along with the productname.

select   
      l.State,
      p.ProductId,
      SUM(f.Profit) as total_profit,
      SUM(f.Sales) as total_sales
from fact as f
  inner join
       Location as l on f.Area_Code = l.Area_Code
  inner join 
       Product as p on f.ProductId = p.ProductId

  group by l.State , p.ProductId
  order by l.State , p.ProductId;

  --Find the maximum profit along with the product ID and producttype.
  
  select  
  f.ProductId, p.Product_Type, MAX(Profit) as max_profit
  from fact as f
  inner join 
            Product as p on f.ProductId = p.ProductId
  group by f.ProductId , p.Product_Type
  order by f.ProductId , p.Product_Type;
  

  --Create a stored procedure to fetch the result according to the product typefrom Product Table

create procedure
     GetProductByType
     @ProductType VARCHAR(100)
AS
   BEGIN
     SELECT *
             from Product
             where Product_Type = @ProductType;
      END;
   
   EXEC GetProductByType @ProductType = 'Coffee';


--Write a query by creating a condition in which if the total expenses is lessthan60 then it is a profit or else loss.

  select Total_Expenses,
     CASE 
         When Total_Expenses < 60 then 'profit'
         else 'loss'
         end as status
  from fact;

  --Give the total weekly sales value with the date and product IDdetails. Useroll-up to pull the data in hierarchical order.
   SELECT 
    DATE_TRUNC('week', date ) AS week_start,
    ProductId,
    SUM(sales) AS total_sales
FROM 
    fact
GROUP BY 
    ROLLUP(DATE_TRUNC('week', date), ProductId)
ORDER BY 
    week_start, product_id;


    /*Apply union and intersection operator on the tables which consist of
attribute area code*/
select Area_Code from fact UNION select Area_Code from Location;

--Change the product type from coffee to tea where product ID is 1 and undo it.
 
UPDATE Product 
 SET Product_Type = 'tea'
 Where ProductId = 1 And Product_Type ='coffee';

 select Product_Type from Product 
 where ProductId='1' ;

 /*Display the date, product ID and sales where total expenses are
between 100 to 200. */

select 
Date , ProductId , SUM(Total_Expenses) as sum_expenses
 from fact
 group by Date,ProductId
 Having SUM(Total_Expenses) Between 100 And 200;

-- Delete the records in the Product Table for regular type.
   Delete from Product 
   where Product_Type = 'Regular';
  
  /*Create a user-defined function for the product table to fetch a particular
product type based upon the user’s preference. */

  CREATE FUNCTION  dbo.UserPreferencePType
  (
      @Product_Type NVARCHAR(255)
  )
  RETURNS TABLE
  AS
  RETURN
  (
     SELECT * FROM Product
     WHERE Product_Type = @Product_Type
  );

 -- Give the total weekly sales value with the date and product IDdetails. Useroll-up to pull the data in hierarchical order.
   SELECT 
    DATE_TRUNC('week', date) AS week_start,
    product_id,
    SUM(sales) AS total_sales
FROM 
    fact
GROUP BY 
    week_start, product_id
ORDER BY 
    week_start, product_id;